# Generated by Django 3.0.2 on 2020-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(upload_to='photogram/'),
        ),
    ]
