# Generated by Django 3.0.2 on 2020-04-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_auto_20200406_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldetails',
            name='status',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
    ]
