# Generated by Django 3.0.2 on 2020-04-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_criminaldetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldetails',
            name='status',
            field=models.CharField(default='Not Found', max_length=10, null=True),
        ),
    ]
