# Generated by Django 3.0.2 on 2020-04-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_auto_20200407_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldetails',
            name='social_media_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
